[package]
name = "gpu_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.3"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.56"
